#!/usr/bin/python

from utils import to_unicode, to_bytes
from cue import read_cue

from optparse import OptionParser, OptionGroup
from subprocess import Popen, PIPE
from tempfile import mkdtemp
from shutil import copyfile
import sys
import os

progname = os.path.basename(sys.argv[0])

def printf(fmt, *args):
	sys.stdout.write(fmt % args)

def printerr(fmt, *args):
	msg = fmt % args
	if msg[-1] != "\n":
		msg += "\n"
	sys.stderr.write("** " + progname + ": " + msg)

def debug(fmt, *args):
	msg = fmt % args
	if msg[-1] != "\n":
		msg += "\n"
	sys.stderr.write("-- " + msg)

try:
	import config
except Exception as err:
	printerr("import config failed: %s", err)
	sys.exit(0)

def quote(s, ch = "\""):
	return s if " " not in s else ch + s + ch

def msf(ts):
	m = ts / (60 * 75)
	s = ts / 75 % 60
	f = ts % 75

	return "%d:%02d:%02d" % (m, s, f)

class TempLink:
	def __init__(self, path, name):
		self.tmpdir = mkdtemp(prefix = "temp-")
		self.linkpath = "%s/%s" % (self.tmpdir, name)

		try:
			os.symlink(path, self.tmpdir + "/" + name)
		except Exception as err:
			os.rmdir(self.tmpdir)
			raise err

	def remove(self):
		os.unlink(self.linkpath)
		os.rmdir(self.tmpdir)

	def __repr__(self):
		return "TempLink('%s')" % self.linkpath

	def __str__(self):
		return self.linkpath

	def __enter__(self):
		return self

	def __exit__(self, *args):
		self.remove()

def print_cue(cue):
	for k, v in cue.attrs():
		printf("%s: %s\n", k.upper(), quote(v))

	for file in cue.files(audio_only = True):
		name = cue.dir + file.name

		printf("FILE %s", quote(file.name))
		if not os.path.exists(name):
			printf(": not exists\n")
		else:
			info = StreamInfo.get(name)
			if not info:
				printf(": unknown type\n")
			else:
				printf(" [%s] (%d/%d, %d ch)\n",
					info.type,
					info.bits_per_sample,
					info.sample_rate,
					info.channels)

		for track in file.tracks(audio_only = True):
			printf("\tTRACK %02d", track.number)
			title = track.get("title")
			if title != "":
				printf(" %s", quote(title))
			printf(": %s -", msf(track.begin))
			if track.end is not None:
				printf(" %s", msf(track.end))
			printf("\n")

			for k, v in track.attrs():
				if k not in ("pregap", "postgap", "title"):
					printf("\t\t%s: %s\n", k.upper(), quote(v))

def parse_args():
	parser = OptionParser(usage = u"Usage: %prog [options] cuefile")
	parser.add_option("--ignore",
		action="store_true", default=False, dest="ignore",
		help="ignore cue parsing errors")

	parser.add_option("--dump",
		action="store_true", default=False, dest="dump",
		help="print the content of cue file")

	parser.add_option("-n", "--dry-run",
		action="store_true", default=False, dest="dry_run")

	conversion = OptionGroup(parser, "Encoding options")

	conversion.add_option("-d", "--dir",
		dest="dir", default=config.DIR, help="output directory")

	conversion.add_option("-C", "--compression", type="int",
		dest="compression", default=config.COMPRESSION,
		help="compression factor for output format")

	parser.add_option_group(conversion)

	format = OptionGroup(parser, "Output format")

	format.add_option("-r", "--sample-rate", type="int",
		dest="sample_rate", default=config.SAMPLE_RATE, metavar="RATE")

	format.add_option("-c", "--channels", type="int",
		dest="channels", default=config.CHANNELS)

	format.add_option("-b", "--bits-per-sample", type="int",
		dest="bits_per_sample", default=config.BITS_PER_SAMPLE, metavar="BITS")

	parser.add_option_group(format)

	tag = OptionGroup(parser, "Tag options")

	tag.add_option("--album", dest="album")
	tag.add_option("--artist", dest="artist")
	tag.add_option("--date", dest="date")
	tag.add_option("--genre", dest="genre")
	tag.add_option("--comment", dest="comment")

	parser.add_option_group(tag)

	return parser.parse_args()

def verify_options(opt):
	if opt.compression is not None and opt.compression < 0 or opt.compression > 8:
		printerr("invalid compression value %d, must be in range 0 .. 8", opt.compression)
		sys.exit(1)

	opt.dir = u"." if not opt.dir else to_unicode(opt.dir)

def get_encoder_formart(opt, info):
	cmd = "flac sox - "
	if opt.compression is not None:
		cmd += "-C %d " % opt.compression
	if opt.sample_rate and opt.sample_rate != info.sample_rate:
		cmd += "-r %d " % opt.sample_rate
	if opt.bits_per_sample and opt.bits_per_sample != info.bits_per_sample:
		cmd += "-b %d " % opt.bits_per_sample
	if opt.channels and opt.channels != info.channels:
		cmd += "-c %d " % opt.channels
	return cmd + "%f"

def filterdir(dir, prefix):
	return sorted(filter(lambda f: f.startswith(prefix), os.listdir(dir)))

def mkdir(path):
	if not os.path.exists(path):
		try:
			os.makedirs(path)
		except OSError as err:
			printerr("make dir %s failed: %s", quote(path), err)
			sys.exit(1)

class StreamInfo:
	__mapping = {
		b"Channels:": "channels",
		b"Bits/sample:": "bits_per_sample",
		b"Samples/sec:": "sample_rate"
	}

	@staticmethod
	def get(name):
		info = StreamInfo()
		proc = Popen(["shninfo", name], stdout = PIPE)
		for line in proc.stdout.readlines():
			data = line.split()
			attr = StreamInfo.__mapping.get(data[0])
			if attr:
				setattr(info, attr, int(data[1]))
			elif line.startswith(b"Handled by:"):
				info.type = to_unicode(data[2])

		if proc.wait():
			return None

		return info

class CueSplitter:
	EXT = ["ape", "flac", "wv"]

	class File:
		def __init__(self, fileobj, name, info):
			self.fileobj = fileobj
			self.name = name
			self.info = info

		def __getattr__(self, attr):
			return getattr(self.fileobj, attr)

	def __init__(self, cue, opt):
		self.cue = cue
		self.opt = opt
		self.tracknumber = 0
		self.tracktotal = sum(
			[len(list(f.tracks(True))) for f in self.cue.files(True)]
		)

		self.tags = {
			"album": self.opt.album or self.cue.get("title"),
			"date": self.opt.date or self.cue.get("date"),
			"genre": self.opt.genre or self.cue.get("genre"),
			"comment": self.opt.comment or self.cue.get("comment")
		}

	def find_realfile(self, name):
		if not name.endswith(".wav"):
			return None

		orig = name.rpartition(".")[0]
		for file in filterdir(self.cue.dir or ".", orig):
			head, _, ext = file.rpartition(".")
			if head == orig and ext in self.EXT:
				return file

		return None

	def open_files(self):
		lst = []

		for file in self.cue.files(True):
			if not file.has_audio_tracks():
				debug("skip file %s: no tracks", quote(file.name))
				continue

			name = self.cue.dir + file.name
			if not os.path.exists(name):
				real = self.find_realfile(file.name)
				if not real:
					printerr("no such file %s", quote(file.name))
					sys.exit(1)
				name = self.cue.dir + real

			info = StreamInfo.get(name)
			if info is None:
				printerr("%s: unknown type", quote(file.name))
				sys.exit(1)

			lst.append(self.File(file, name, info))

		return lst

	def shntool_args(self, tool, info):
		encode = get_encoder_formart(self.opt, info)
		return [tool, "-w", "-d", self.opt.dir, "-o", encode]

	def get_track_name(self, track):
		self.tracknumber += 1
		title = track.get("title") or "track"
		return "%02d.%s.flac" % (self.tracknumber, title)

	def tag(self, track, path):
		self.tags.update({
			"tracknumber": "%02d" % self.tracknumber,
			"tracktotal": "%02d" % self.tracktotal,

			"title": track.get("title"),
			"artist": self.opt.artist or track.get("performer") or self.cue.get("performer"),
		})

		args = ["metaflac", "--remove-all-tags", "--import-tags-from=-", path]
		printf("Tag [%s] : ", path)
		sys.stdout.flush()

		proc = Popen(args, stdin = PIPE)
		for k, v in self.tags.items():
			if v is not None and v != "":
				proc.stdin.write(to_bytes("%s=%s\n" % (k.upper(), v)))
		proc.stdin.close()

		if proc.wait():
			printf("FAILED\n")
			sys.exit(1)

		printf("OK\n")

	def copy_file(self, file):
		noteq = lambda a, b: a and a != b

		if file.info.type != "flac":
			return False
		if noteq(self.opt.sample_rate, file.info.sample_rate):
			return False
		if noteq(self.opt.bits_per_sample, file.info.bits_per_sample):
			return False
		if noteq(self.opt.channels, file.info.channels):
			return False

		track = list(file.tracks(True))[0]
		trackname = self.get_track_name(track)
		dest = os.path.join(self.opt.dir, trackname)

		if self.opt.dry_run:
			printf("Copy [%s] --> [%s]\n", file.name, dest)
			return True

		printf("Copy [%s] --> [%s] : ", file.name, dest)
		sys.stdout.flush()

		try:
			copyfile(file.name, dest)
		except Exception as err:
			printf("FAILED: %s\n", err)
			sys.exit(1)
		else:
			printf("OK\n")

		self.tag(track, dest)

		return True

	def convert_file(self, file):
		track = list(file.tracks(True))[0]
		trackname = self.get_track_name(track)

		args = self.shntool_args("shnconv", file.info)

		if self.opt.dry_run:
			name = "link to " + quote(file.name, "'")
			debug("run %s", " ".join(map(quote, args + [name])))
			return

		try:
			link = TempLink(os.path.abspath(file.name), trackname)
		except OSError as err:
			printerr("create symlink %s failed: %s", quote(trackname), err)
			sys.exit(1)

		ret = Popen(args + [str(link)]).wait()
		link.remove()

		if ret:
			printerr("shnconv failed: exit code %d", ret);
			sys.exit(1)

		self.tag(track, os.path.join(self.opt.dir, trackname))

	def split_file(self, file, points):
		args = self.shntool_args("shnsplit", file.info) + [file.name]

		if self.opt.dry_run:
			debug("run %s", " ".join(map(quote, args)))
			return

		proc = Popen(args, stdin = PIPE)
		proc.stdin.write(to_bytes("\n".join(map(str, points))))
		proc.stdin.close()

		if proc.wait():
			printerr("shnsplit failed: exit code %d", proc.returncode)
			sys.exit(1)

		splitted = filterdir(self.opt.dir, "split-track")
		for track, filename in zip(file.tracks(True), splitted):
			trackname = self.get_track_name(track)
			dest = os.path.join(self.opt.dir, trackname)

			printf("Rename [%s] --> [%s] : ", filename, trackname)
			try:
				os.rename(os.path.join(self.opt.dir, filename), dest)
			except OSError as err:
				printf("FAILED: %s\n", err)
				sys.exit(1)
			else:
				printf("OK\n")

			self.tag(track, dest)

	def split(self):
		if not self.opt.dry_run:
			mkdir(self.opt.dir)

		for file in self.open_files():
			points = list(file.split_points(file.info))
			if not points:
				if not self.copy_file(file):
					self.convert_file(file)
			else:
				self.split_file(file, points)

def main():
	options, args = parse_args()
	verify_options(options)

	if len(args) != 1:
		printf("Usage: %s [options] cuefile\n", progname)
		return 1

	def on_error(err):
		printerr("%d: %s\n" % (err.line, err))
		if not options.ignore:
			raise StopIteration

	cuepath = to_unicode(args[0])
	try:
		cue = read_cue(cuepath, on_error=on_error)
	except StopIteration:
		return 1
	except IOError as err:
		printerr("open %s: %s", err.filename, err.strerror)
		return 1
	except Exception as err:
		printerr("read_cue failed: %s: %s\n", err.__class__.__name__, err.filename)
		return 1

	cue.dir = os.path.dirname(cuepath)
	if cue.dir:
		cue.dir += "/"

	if options.dump:
		print_cue(cue)
	else:
		CueSplitter(cue, options).split()

	return 0

if __name__ == '__main__':
	sys.exit(main())
